### ISSUE TITLE
Create 3D globe

### ISSUE THREAD

**Issue by ifr4h** [i-f-r-a-h/Crisis_Connect#5]
**__Task Description__**
Create a low poly globe 

**Steps to Follow**
- [ ] Create a modal in blender 
- [ ] Export and optimize the modal
- [ ] Add modal to a new component 

**How to access files for this task**

**Additional info/tips**
